apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microscaling
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microscaling
    spec:
      containers:
        - name: microscaling
          image: microscaling/microscaling:sqs-test
          env:
            - name: MSS_USER_ID
              value: ***YOUR_USER_ID***
            - name: MSS_SCHEDULER
              value: KUBERNETES
            - name: NSQ_STATS_ENDPOINT
              value: "nsq.default.svc.cluster.local:4151"
          imagePullPolicy: Always
