apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq
  name: nsq
spec:
  ports:
  - port: 4150
    protocol: TCP
    targetPort: 4150
    name: tcp
  - port: 4151
    protocol: TCP
    targetPort: 4151
    name: http
  selector:
    app: nsq
  sessionAffinity: None
  type: ClusterIP
